// This file is auto-generated by scripts/setup_agent.py
// Run the setup script once after deploying the backend to populate agentId.
// DO NOT edit manually.
window.DEMODENTAL_CONFIG = { agentId: "" };
